name: Deployment
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@dev3dbody'
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: npm install
#      - name: E2E Test (cypress.io)
#        uses: cypress-io/github-action@v2
#        with:
#          start: yarn start
#          wait-on: 'http://10.1.0.4/'
#          wait-on-timeout: 120
#          browser: chrome
#          config: baseUrl=http://10.1.0.4
      - run:
          name: Add build number in browser window title
          command: sed -i -e 's/%VERSION%/'"$CIRCLE_BUILD_NUM"'/g' public/index.html
      - name: Build
        run: npm run build
        env:
          CI: false
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
